### ISSUE TITLE
Issues with movie playback in Scratchpads

### ISSUE THREAD

**Issue by informatics-dev** [NaturalHistoryMuseum/scratchpads2#4210]
- Original ID: 3047
 - Added by **Dimitrios Koureas**
 - Scratchpads URL: http://ciliateguide.myspecies.info

### Description:
- Video cannot be reproduced in the colorbox overlay window when clicking on videos (.mov) in the media galleries
http://ciliateguide.myspecies.info/gallery

- Videos (.mov) embedded in pages is replaced with a generic image and is not reproducible
http://ciliateguide.myspecies.info/ciliates-activated-sludge#

**Comment by poospiza** [comment]
We would very much like to be able to reproduce video on our site but due to the issues above it is not an option at present and we are beginning to consider an alternative path. Do you expect that the reproduction of video in Scratchpads will be improved in the future?

It would be useful for us to be able to tag videos with keywords similar to Image files (The keywords that are listed as Terms in the Media Gallery left menu).
Thank you
Nicholas
http://ethoikos.myspecies.info/

**Comment by alycejenni** [comment]
- colorbox overlay now works
- video embedding issue is probably a duplicate of #4797
