### ISSUE TITLE
Dockerised Scratchpads failing on Kubuntu

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/scratchpads2#5655]
![image](https://user-images.githubusercontent.com/81690/47870062-7f2fb780-de00-11e8-90b5-00488520316f.png)

**Comment by s-bolshakov** [comment]
I got this error on the Kubuntu 18.04. It turns out that docker-sync was installed on the system. When I deployed scratchpads to the clean system with docker and docker-compose but without docker-sync - the installation was successful. I apologize for the trouble because I wasn't attentive to the instructions.

**Comment by benscott** [comment]
Great, glad you got it sorted.
