### ISSUE TITLE
Character editor vanished

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5720]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

In Structure > Tools > Scratchpad Tools section: There should be a Character editor module, as specified in https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Add-a-character-project
However, that module has vanished.

**Comment by jrdh** [comment]
Hi Archilegt, thanks for raising this. The character editor module has been disabled since June 2013 (https://github.com/NaturalHistoryMuseum/scratchpads2/issues/4190) and needs to be redeveloped before it can be made active again. Currently we're working on catching up with the large backlog of issues and therefore I'm not sure when this module will get looked at, unfortunately.

**Comment by scratchpads** [comment]
Comment by [Archilegt](http://myriatrix.myspecies.info/user/2)

Hey, thank you for your reply. Please, then try at least to fix  the imports from EoL and from WoRMS. Importing is the most basic functionality that new Scratchpads need. If that is also going to take long time, then please consider to create a short tutorial on how to import a classification directly from TCS provider URL and show a practical example. I have been unable to find those resources online. Thank you again! :-)

**Comment by alycejenni** [comment]
Initial issue is unlikely to be fixed any time soon; second issues are duplicates of #5718 and #5719.
