### ISSUE TITLE
Duplicated (Triplicated? Quadricated?) Images on taxon pages 

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5737]
http://bio.acousti.ca/taxonomy/term/246/media

<img width="799" alt="screenshot 2018-12-22 at 11 51 35" src="https://user-images.githubusercontent.com/929684/50374053-f0f5d780-05df-11e9-8bf4-201a6957155b.png">

**Comment by benscott** [comment]
Added group by file ID to the view. Does that fix it for you?  If so, I'll add it to the default view code.

**Comment by edwbaker** [comment]
Yes, it's fixed if I log in.

**Comment by jpsullivan65** [comment]
Important to note that the duplication only happens when adding media via "Add file" pull-down link from the species media window.  This has been a huge annoyance for years now, sadly.  Can anything be done about all the duplicates that already exist?  For now, if you delete one dup, both disappear.

**Comment by benscott** [comment]
Group by doesn't completely fix the issue raised by @jpsullivan65 - requires a better implementation.

**Comment by jrdh** [comment]
This will be resolved in https://github.com/NaturalHistoryMuseum/scratchpads2/pull/6129 but for @edwbaker and @jpsullivan65's scratchpads I've applied the fix manually to the `species_media` view. Sorry this took so long to resolve!

**Comment by poospiza** [comment]
> This will be resolved in #6129 but for @edwbaker and @jpsullivan65's scratchpads I've applied the fix manually to the `species_media` view. Sorry this took so long to resolve!

I don't suppose you could apply the fix manually to the species pages on our site as well :-) ? We have had the same problem for a long time as well and it frankly does not look very professional with doubles all over the place. http://ethoikos.myspecies.info/

**Comment by jrdh** [comment]
Fix applied @poospiza, have you got any examples of where it was causing problems just so I can check it worked?

**Comment by poospiza** [comment]
> Fix applied @poospiza, have you got any examples of where it was causing problems just so I can check it worked?

Thanks for applying the fix!
Sorry I don't have any examples noted down (its a long time ago I last looked at it) but there were plenty. I've done a check of the species pages and have not found doubles where I am pretty sure there were before. 

But
I have also tried to add a photo and attach it to both a species page and to a specimen page. http://ethoikos.myspecies.info/content/ethoikos-ebd-15667. Photo guid "2aa38e1c-cace-4faa-9e2a-9d3a3bcb2eef"
The photo does not then appear twice in the species page as it did before. But when I export a list of all images, using the attached template excel file (generated using the Import module) I noticed something I did not expect. The value in field "Taxonomic name (Name)" has the common name repeated: "Podarcis  sicula|Podarcis  sicula". With two spaces between the genus and species name, which also isn't ideal imo.

I then looked closer at my photos in the excel template file and it turns out that there are several examples of double or triple values in the field "Taxonomic name (Name)" and in a few cases the field has two or three different taxon names for a single photo. Maybe because I over time have changed the original taxon name attached to the image.
The consequence seems to be that the same image is displayed for more than one species. The most evident example is the Genus Lestes where the same image is shown for three different species and the field "Taxonomic name (Name)" has all three taxon names listed for the photo "Lestes  virens|Lestes  barbarus|Lestes  viridis" (Should be Lestes virens)
photo guid:  "5f52781f-69ea-47f1-81d8-a418d798430c"
http://ethoikos.myspecies.info/fauna-checklist-la-selva/lestes 
The photo has not been attached to a specimen page.

It seems that the previous taxon names  assigned to the photo are retained which doesn't seem right.

Nicholas
[file_importer_image_xls(1).xlsx](https://github.com/NaturalHistoryMuseum/scratchpads2/files/4139187/file_importer_image_xls.1.xlsx)
