### ISSUE TITLE
wallaceletters.info not being indexed either!

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5740]
- Added by [George Beccaloni](http://wallaceletters.info/user/2)
- Scratchpad: [The Alfred Russel Wallace Correspondence Project](http://wallaceletters.info)

### Description:

My Scratchpad wallaceletters.info is not being indexed by Google - the same problem as with my other Scratchpad wallacefund.info Very odd this, since other Scratchpads like Solanaceae Source are being indexed... I urgently need you to allow Google bots to index my sites as people cannot find them easily..

**Comment by jrdh** [comment]
Hi George,

Just to follow up on Vince's reply via email, the site does seem to be being indexed as I can see it when searching for `The Alfred Russel Wallace Correspondence Project` or indeed `Alfred Russel Wallace Website` like Vince suggested. It's certainly possible, again as Vince suggested, that the site has been affected by the recent issues on Scratchpads with bots.

You said that you `"discovered that it isn’t now indexed by Google because of “Server error (5xx)”"` - was that something you could see in the Google interfaces? And is that still the case?

**Comment by edwbaker** [comment]
There are a number of pages (e.g. the homepage) that seem to have been dropped from the Google Index. George has sent me screenshots from his Google Search Console showing several hundred 500 server error messages.

**Comment by jrdh** [comment]
George has confirmed via email that this has been resolved.
