### ISSUE TITLE
Continual AJAX errors on BioAcoustica

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#5762]
Sometimes this happens every time (e.g. taxonomy editing), other times it is intermittent (e.g. node import).

**Comment by jrdh** [comment]
Fixed in https://github.com/NaturalHistoryMuseum/scratchpads2/pull/5764. The reason this was working on the node import is presumably because under those circumstances the [`if ($parts[0] == "node") {`](https://github.com/NaturalHistoryMuseum/scratchpads2/blob/master/sites/all/modules/custom/wavesurfer/wavesurfer.module#L165) passed and hence nothing was printed out.

**Comment by jrdh** [comment]
Will close when released
