### ISSUE TITLE
problems updating custom data sheet

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5771]
- Added by [Gontran Sonet](http://jemu.myspecies.info/user/2)
- Scratchpad: [Joint Experimental Molecular Unit (JEMU)](http://jemu.myspecies.info)

### Description:

Dear Scratchpad team,
I would like to update my 'primer database' (custom content type) http://jemu.myspecies.info/#overlay=import/node_importer_primer_db_xls' but I get an error message: "Unrecognized token 00 in formula"
I already did this in the past without any problem and I do not know why it is not working anymore.
Thank you for your help!

**Comment by jrdh** [comment]
Hi Gontran,
It looks like the problem is with the xls file as it seems our excel reading library isn't capable of reading it. I did notice that when I open up the last file you attempted to upload (http://jemu.myspecies.info/system/files/feeds/node_importer_primer_db_20190116_0.xls) it warns me that the spreadsheet contains links to other files. I tried saving it as an `ods` and then resaving that as an `xls` before reuploading in my dev environment and it worked correctly. Perhaps it's worth you copying the data into a clean template and trying again?
