### ISSUE TITLE
Remove odd formatting from Biblio entries?

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5845]
- Added by [lukas.scharer](http://macrostomorpha.info/user/2)
- Scratchpad: [Macrostomorpha](http://macrostomorpha.info)

### Description:

The Bibliography that I have entered largely in 2008 now has some odd formatting in some of the fields, which I suspect are a carry-over effects from earlier Scratchpad versions.
For example the Abstract field here (and in many other cases) 
http://macrostomorpha.info/node/986
has odd `<address>` tags, which may date from when these fields were entered differently (I think they used to allow be html-like text entry).
 Could you possibly fix this in an automated way? Thanks! Cheers, Lukas

**Comment by scratchpads** [comment]
Comment by [lukas.scharer](http://macrostomorpha.info/user/2)

Interestingly, these <-address-> tags (hyphens added deliberately) also seem to work in the above comment text.

**Comment by alycejenni** [comment]
(I've updated the original comment to show the `<address>` tags, which Github reads as xml and hides)

**Comment by alycejenni** [comment]
Sorry it's taken so long, but I've now done this - please let me know if there are any problems! 211 nodes had to be edited, and I have all the previous and new values backed up if you need/want to take a look.

The tags were mostly `<address></address>`, but there were also some unnecessary `<p>` and `<span>` tags, which I've also stripped out. I've left in the `<em>` tags.

I also had to change the format to filtered HTML for the nodes I edited (most had the abstract set to plaintext, which is why all the tags were visible).
