### ISSUE TITLE
Taxon misspelling + Literature links

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5849]
- Added by [Darwyn Sumner](http://micropezids.myspecies.info/user/2)
- Scratchpad: [European Micropezids & Tanypezids](http://micropezids.myspecies.info)

### Description:

Correct a taxon misspelling and it appears in the tree in italics.
Will not connect to the Literature keyword under the corrected spelling, got to use the misspelled binomial.
How to fix this?

**Comment by jrdh** [comment]
Hi Darwyn, is this _Micropeza kawalli_ or a different taxon?

**Comment by alycejenni** [comment]
Closing due to lack of information

**Comment by Archilegt** [comment]
It is correct that the misspellong appears in italics after being edited and corrected.
Exact strings will always connect with each other, as names work as unique identifiers. That's the main rationale behind Scratchpads. So a misspelled name can only connect to its corresponding misspelled keyword, not to a different one. You can always add more keywords and taxon tags to literature in order to improve matches.
