### ISSUE TITLE
Old backups not being deleted

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5882]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

I still can't download the latest backup for the site. It does not exist when I click on the link.

The old backups are not deleting automatically, so I can't  request new one. 

The oldest is from 20th November.

Thanks

**Comment by jrdh** [comment]
Hi Anna,
I've removed a couple of backups so you should be able to make more now. I'm working on removing all the old backups now so that this isn't a problem going forward. Seems like although we say we delete backups older than a week we definitely aren't doing that right now... Hopefully this will be resolved properly soon!
