### ISSUE TITLE
Content not available to anonymous users

### ISSUE THREAD

**Issue by alycejenni** [NaturalHistoryMuseum/scratchpads2#5900]
The main content of this page is not available to anonymous users:
http://mosquito-taxonomic-inventory.info/simpletaxonomy/term/6483

- permissions are set to public
- it appears to be the only page with this problem
- the [associated node](http://mosquito-taxonomic-inventory.info/node/12833) _is_ visible to anonymous users (I'm sure it wasn't earlier but it is now)
- I can't find any errors in the apache logs

**Comment by jrdh** [comment]
So this is because the node access is missing from the node associated with the term, i.e.:

```sql
select * from node_access na join taxonomy_index ti on ti.nid = na.nid where ti.tid = 6483;
```

produces no results.

Not sure how this happened, but rebuilding the permissions fixes the issue (http://mosquito-taxonomic-inventory.info/#overlay=admin/reports/status/rebuild (safe link, this won't run the rebuild, you have to click a button on that page!)) and seems to be a common maintenance task on drupal installs (though not something you'd want to to frequently on a cron).

There are 31 new rows added to the `node_access` table after rebuilding so this fixes more stuff than just this, here's some info:

- 11 terms are fixed: `6275, 6052, 6054, 8585, 6223, 6128, 6163, 6483, 6231, 6265, 6266`
- 31 nodes are fixed: `12296, 910, 12438, 928, 13472, 1060, 1062, 937, 11690, 11691, 10798, 11086, 13518, 13519, 13520, 13521, 13522, 13523, 13524, 13525, 11351, 13526, 13527, 13528, 13529, 13530, 13531, 1000, 10864, 11761, 11642`
