### ISSUE TITLE
No tabs in Edit Taxon Description

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5903]
- Added by [Charlie Perez](http://floraofgibraltar.myspecies.info/user/5)
- Scratchpad: [Flora of Gibraltar ](http://floraofgibraltar.myspecies.info)

### Description:

 the site floraofgibraltar.myspecies.info  The tabs in the Edit Taxon description i.e. Overview, Conservation, Description, Evolution & Sys, Ecology & Distribution and Relevance, no longer appear in the edit settings despite several boxes ticked in the configuration page for Taxon description editor settings.

**Comment by alycejenni** [comment]
Hi,
Thanks for raising this! Bizarrely, this was actually caused by your maps settings:
![image](https://user-images.githubusercontent.com/23579762/55172720-61c60600-5172-11e9-9bf2-3512e8b000a3.png)

I removed the `° N` and `° W` symbols and it now seems to work as expected. I imagine your maps weren't working either, so hopefully that should be working too now.

Some technical details:
Leaflet couldn't handle the `° N` and `° W` symbols, so when that broke it prevented other scripts from running (including the one that adds the `non_empty_tab` - `spm_config.js`). Without `.non_empty_tab`, the tabs have `display:none;` set as the style.
