### ISSUE TITLE
Taxonomy tree page not accible

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5935]
- Added by [Marco Gaiani](http://neotropicalcicadellidae.myspecies.info/user/2)
- Scratchpad: [Neotropical Leafhoppers](http://neotropicalcicadellidae.myspecies.info)

### Description:

The taxonomy page tree of http://neotropicalcicadellidae.myspecies.info gives me a: "Access denied. You are not authorized to access this page." message. Any ideas

**Comment by jrdh** [comment]
Hi Marco, not sure what happened here but I've now resolved it :slightly_smiling_face:.

Info for future maintainers: there seemed to be a problem with the `taxonomy/term/%` entry in the `menu_router` table. The entry looked like this on this site:

```
| path            | load_functions                       | to_arg_functions | access_callback | access_arguments | page_callback                 | page_arguments | delivery_callback | fit | number_parts | context | tab_parent | tab_root        | title | title_callback | title_arguments | theme_callback | theme_arguments | type | description | position | weight | include_file |
| taxonomy/term/% | a:1:{i:2;s:18:"taxonomy_term_load";} |                  | 0               | a:0:{}           | scratchpads_species_term_page | a:0:{}         |                   |   6 |            3 |       0 |            | taxonomy/term/% |       | t              |                 |                | a:0:{}          |    6 |             |          |      0 |              |
```

Few problems here:

- `access_callback` is set to 0 so this will always come back with access denied
- `access_arguments` are also not set correctly
- `page_arguments` are not set correctly resulting in `scratchpads_species_term_page` failing even if the `access_callback` value is set to `1` because not enough arguments are passed through.
- no title values set (`title`, `title_callback` and `title_arguments`)
- `include_file` is missing a value

All of these are corrected with this SQL:

```sql
update menu_router set access_callback = 'user_access', access_arguments = 'a:1:{i:0;s:14:"access content";}', page_arguments = 'a:1:{i:0;i:2;}', title = 'Taxonomy term', title_callback = 'taxonomy_term_title', title_arguments = 'a:1:{i:0;i:2;}', include_file = 'sites/all/modules/custom/leftandright/taxonomy.pages.inc' where path = 'taxonomy/term/%';
```

The values for that update statement have been pulled from other working scratchpads.

Perhaps this was caused during an update to the taxonomy module? :confused:

**Comment by scratchpads** [comment]
Comment by [Marco Gaiani](http://neotropicalcicadellidae.myspecies.info/user/2)

Thanks for the great work! But....
I just updated my taxonomy tree with an XLS file import and we are back to the same "Access denied" message. So perhaps the root of the problem is in the update as you suggested on your message
