### ISSUE TITLE
REFINDIT and BHL synergy

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#5944]
- Added by [Christos Georgiadis](http://greekants.myspecies.info/user/2)
- Scratchpad: [Ants of Greece](http://greekants.myspecies.info)

### Description:

Has access to these data providers been revoked?

**Comment by jrdh** [comment]
Hi Christos, they should both work correctly - though it does seem that the ReFindIt API is responding quite slowly to requests currently. For example on this page: http://greekants.myspecies.info/taxonomy/term/9/literature the BHL links load but the ReFindIt links don't, possibly because the time taken to load them exceeded our specified timeout of 5 seconds - I'll look at increasing this. Otherwise, this seems to be working fine.

**Comment by Chrisis21** [comment]
Sorry to bother again Josh but unfortunately it's not working...
![image](https://user-images.githubusercontent.com/41307327/59427830-9dc14c80-8dec-11e9-8f6f-525d9702db0c.png). And I have checked that there are indeed references in both...

**Comment by jrdh** [comment]
Hi @Chrisis21, thanks for the update, much appreciated! The changes I've made haven't been released yet so might at least explain the ReFindIt failure, interesting that BHL is also having issues now too though. I'll take another look and see if we need to extend the BHL timeout too.

**Comment by jrdh** [comment]
I've made some additional changes on this PR: https://github.com/NaturalHistoryMuseum/scratchpads2/pull/5946, hopefully, once they are reviewed and released they should make the interface more consistent for you. I'll update this issue once the changes have been released.

**Comment by scratchpads** [comment]
Comment by [Christos Georgiadis](http://antsme.myspecies.info/user/2)

Wow! Thank you so much for keeping up with it! I will let you know as soon as I see any significant changes to the page. Thank you again for all your efforts!

**Comment by PaulKiddle** [comment]
@Chrisis21 This change has been released now so you should see this problem fixed.
