### ISSUE TITLE
Recent page feature not working?

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6130]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

Today I created a Lexicon and made it appear in the front page as tab "Morphology". However, that new page is not showing in the "Recent page" frontpage widget, just like other pages newer than "About us" never showed up. Any idea why is this happening?

**Comment by jrdh** [comment]
Hi Archilegt,
Thanks for getting in touch. The reason "Morphology" doesn't appear in the "Recent pages" block is that it's not a page, it's a vocabulary. This means it appears in the "Recently added taxon descriptions" block instead of the "Recent pages" block. Hope that helps to explain what's going on.
