### ISSUE TITLE
Recognition of punctuation differences needed

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6149]
- Added by [Archilegt](http://myriatrix.myspecies.info/user/2)
- Scratchpad: [Myriatrix](http://myriatrix.myspecies.info)

### Description:

There is no recognition of punctuation differences among two otherwise identical spellings. That needs to be implemented for the "Associated accepted name" feature to work correctly. Example:
The onychophoran Mongeperipatus keköldi has just been described. The spelling of the specific epithet is not Code-compliant and has to be changed to kekoldi (not "kekoeldi"). However, the AAN feature does not recognize that ö-o difference and it is impossible to save the information on the correct associated name. Please, take a look at this issue. Thanks!

**Comment by alycejenni** [comment]
If I'm understanding this issue correctly (you can't add _Mongeperipatus kekoldi_ as an AAN to _Mongeperipatus keköldi_?), I believe I've tracked down the problem but I'm unable to recreate it locally (yet).

This is because - for some reason - the term ID is not being added to the AAN when it's autocompleted. When you select the name, it should have an ID in square brackets after it, e.g.:
![image](https://user-images.githubusercontent.com/23579762/78157751-469e6e00-7438-11ea-8bdf-1ad8894ac7cb.png)
And that's what helps differentiate items with the "same" spelling.

I'll continue to try and work out where this is going wrong on your scratchpad, but as a workaround in the meantime, you can manually add the term ID (just by typing it in). You can find the ID of a term by editing it and looking in the top left of this box:
![image](https://user-images.githubusercontent.com/23579762/78158270-ebb94680-7438-11ea-98fc-f968697b7c67.png)
e.g. here the ID is 31.

(NB: the screenshots here are from my local dev scratchpad, not from your scratchpad, so the IDs will not be the same!)

**Comment by Archilegt** [comment]
Hi @alycejenni 
That seems like a great solution! I understood your explanation and how to differentiate the involved names.
About the origin of the issue: Do you think that it is due to ö, ü and similar characters not being included in the default English alphabar values of the involved fields? If so, I have no idea how to change those. I only know how to include additional letters into lexicons, via Configuration, System, Lexicon settings, Alphabar settings. However, the taxonomic backbone is not supposed to act as lexicon.

**Comment by alycejenni** [comment]
In terms of why ö=o, I believe that's because of the [collation settings](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html) in MySQL (the database).

As for why the term ID isn't being added - I don't know yet!
