### ISSUE TITLE
Biblio edits

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6190]
- Added by [vblago](http://sciaroidea.info/user/9)
- Scratchpad: [Fungus Gnats Online](http://sciaroidea.info)

### Description:

If you edit bibio node (update publication details, for example) and upload a file to attach at the same time, edits are lost

**Comment by Archilegt** [comment]
This bug is related to #6127 . It was reported by me as a preview bug but it was probably generated or co-generated by already uploaded pdfs. For the time being, I am adding pdfs without making other edits at the same time. Looking forward to have it fixed and be able to enter data and upload attachments in one step.
