### ISSUE TITLE
Valid DOI gives error

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6192]
10.1577/1548-8675(2002)022<0208:tgctrt>2.0.co;2

This DOI was provided from Crossref metadata, but cannot be imported into Scratchpads.

Error given is: "This does not appear to be a valid DOI name"

**Comment by edwbaker** [comment]
Taxon has been added in preparation

**Comment by Archilegt** [comment]
@edwbaker , in which paper or resource is that DOI mentioned? Also, note that while all DOIs may be registered in doi.org, not all DOIs are registered in CrossRef. Scratchpads DOI service is based in CrossRef only. Unless the service is expanded to other parties, DOIs that are not registered in CrossRef won't populate anything in Scratchpads. That is the case of ResearchGate DOIs, or at least it was the last time I checked.

**Comment by edwbaker** [comment]
It comes from a download of the CrossRef metadata here: https://www.crossref.org/blog/free-public-data-file-of-112-million-crossref-records/

It resolves fine using doi.org, just not on Scratchpads.

**Comment by Archilegt** [comment]
@edwbaker , I checked the paper. The DOI resolves correctly at doi.org, so they do have it registered. You may want to ask Wiley how they created those weird DOIs for old papers, where is that metadata stored, and why it is not registered in CrossRef being that they are members.

**Comment by Archilegt** [comment]
@alycejenni , this is not a Scratchpads error. SP cannot resolve DOIs if the metadata is not stored in CrossRef, which is the case.

**Comment by edwbaker** [comment]
@alycejenni @Archilegt It is registered in CrossRef. I found it by searching the CrossRef metadata. So it is a Scratchpads issue.

**Comment by Archilegt** [comment]
@edwbaker I saw now the blog post you cited. Please note that having that DOI stored in CrossRef does not imply that it will parse, even inside CrossRef. If you take the time to try parsing the DOI in CrossRef you will notice that CrossRef won't find it. Again, this is not a SP error.
According to the blog post that you cited, "If an error in the metadata is found, please report it directly to the publisher to correct". Wiley is to be contacted first for a DOI check, then CrossRef and after they confirm that the issue has been solved (e. g. the DOI correctly parsing within CrossRef) you could check again. Otherwise you will get the SP team crazy trying to solve a problem that is not in their side.

**Comment by Archilegt** [comment]
CrossRef Metadata Search finds zero results for that DOI:
![imagen](https://user-images.githubusercontent.com/60008120/79321080-1ad8b900-7f0b-11ea-905d-917faeaa4a70.png)

**Comment by alycejenni** [comment]
The crossref UI can't parse it, but the API can: https://api.crossref.org/works/10.1577/1548-8675(2002)022%3C0208:tgctrt%3E2.0.co;2
So unfortunately it probably is a Scratchpads error (though I'll have to investigate more thoroughly before I can say for certain, because clearly crossref have some of their own issues with this DOI).

**Comment by edwbaker** [comment]
@alycejenni I would assume just adding the < and > in biblio_crossref_form_biblio_node_form_submit() ?

**Comment by edwbaker** [comment]
In fact it might be good to submit to the API and seeing if there is a result before the giving any error. The blog post in the source code seems to suggest there may well be other types of error.
