### ISSUE TITLE
Biblio data not saving on first attempt

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6266]
- Added by [Anna](http://icgf.myspecies.info/user/36)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](http://icgf.myspecies.info)

### Description:

When adding data to Biblio document pages, the following fields are only saved on the second attempt: YEAR OF PUBLICATION, CONFERENCE NAME, DATE PUBLISHED and CONFERENCE LOCATION. 

The first time you input the data, you click save, but they are lost. You have to enter the data again for it to save.

**Comment by Archilegt** [comment]
Hi Anna,
The data is not saving because you are probably also adding an attachment during the first round of data entry. This bug has been reported MULTIPLE times (#6244 , #6190 , #6127 ) and I would really appreciate that it is taken seriously and fixed. It affects all Scratchpads and it cannot be so hard to fix. So I hope that someone finally listens and fixes this bug!

**Comment by annanc14** [comment]
Hello, thanks for the reply. 
I don't think the problem occurs only after adding attachments. I usually add the data first, save it, then add the attachments later..... Still though, it can sometimes loose half the data...

**Comment by Archilegt** [comment]
Hi Anna,
The other thing that I knows triggers the bug is previewing the bibliographic reference. I mentioned that problem in issue #6127.
Hopefully it will be taken care off, as so many users have mentioned it already.
Nice weekend to you,
Charlie

**Comment by alycejenni** [comment]
This should've been fixed by #6296 (please comment/reopen if not!)

**Comment by Archilegt** [comment]
Hi @alycejenni,
Just confirming that I have databased quite a few references after the fix, and it is working smoothly. I can go back and forth, filling the tabs in any order, adding attachments, etc., without fields disappearing. The only thing that I have not tested is the "preview" option, because I didn't need it. I will let you know if any issue appears. Many thanks for all the support!
