### ISSUE TITLE
Host server not responding 

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6289]
- Added by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)
- Scratchpad: [Agromyzidae of Great Britain & Ireland ](http://agromyzidae.myspecies.info)

### Description:

I am unable to work on my site without it failing to save, stating that the NHM server is busy or unable to reload. This often means I lose a lot of work which is so frustrating. Is this problem likely to be resolved?

Thanks.

**Comment by alycejenni** [comment]
We restarted a server yesterday in the hopes of fixing this issue - let us know if you're continuing to have problems!

**Comment by scratchpads** [comment]
Comment by [Barry Warrington](http://agromyzidae.myspecies.info/user/2)

Thank you. I’ll let you know if it happens again.

**Comment by BarryWarrington** [comment]
The same issue happened several times today, with the attached error message. I lose vast amounts of work each time this happens when I click save.

![Untitled](https://user-images.githubusercontent.com/75427252/101065941-afbd1f00-358d-11eb-93b6-1c845813563f.jpg)

**Comment by alycejenni** [comment]
Does this happen when you're doing something in particular, or does it just seem to happen randomly?

**Comment by BarryWarrington** [comment]
It happens the most when I am editing the species description - for
example, when I am clicking all the UK vice counties where a species is
known from (I can select 50 VC's, then click save but it crashes and all
the selecting is lost) or when I am adding hyperlinks to a large list of
host plants for a species (I can add 30 hyperlinks, click save and it
crashes, losing all the hyperlinks). It does happen though at other times
too, just today I can click on a species on the taxonomic tree and it'll
say the same error message.

Thanks,

Barry.
National Agromyzidae Recording Scheme Organiser
www.brc.ac.uk/scheme/national-agromyzidae-recording-scheme

To receive the NRS Newsletter, just send an email to be added to the
mailing list.

**Comment by alycejenni** [comment]
Hi Barry, sorry this has taken a few days. I think we've managed to track down the source of the problem, and unfortunately it appears to be that you've just been exceptionally unlucky with timings - we're running migrations on a lot of scratchpads at the moment and that requires a lot of automated restarts. Mostly these are very quick and won't cause any problems for anyone, but you may have just happened to click "save" at precisely the wrong moment several times!

There's not really anything we can do about the root cause of the problem, but the migrations are going to be paused for the next few weeks (until after Christmas) so you should be able to edit without any problems until then. Let us know if you're still having problems.

**Comment by BarryWarrington** [comment]
Hiya,

Ok, thanks - just bad timing then!

As a side note, how will I know when the map issue (disable map auto zoom)
I reported has been sorted?

Thanks again,

Barry.
National Agromyzidae Recording Scheme Organiser

**Comment by alycejenni** [comment]
You can find that here: #6283
Updates will go in there. :)

**Comment by therobyouknow** [comment]
On basis that this has been implemented I'm assuming it has been released so I have removed it from current release sprint because completed/done/closed.  Thank you for all your work on it.
