### ISSUE TITLE
Biblio import from DOI can end in multiple concatenated URLs/DOIs

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/scratchpads2#6299]
See e.g. http://bio.acousti.ca/content/bioacoustics-poorly-known-poecilimon-taxa-insecta-orthoptera-tettigoniidae-redescriptions-p#

Related display issue in Taxon Description content type (see image; http://bio.acousti.ca/taxonomy/term/168/descriptions)

![Screenshot 2020-12-09 at 11 55 17](https://user-images.githubusercontent.com/929684/101627038-aad8ef00-3a15-11eb-88ed-c61eb1af2f56.png)

**Comment by Archilegt** [comment]
Hi all,
I have reported this issue almost one year ago, on Feb 17, 2020. See Errors in DOI mapping #6147
I also discussed this problem with Pensoft staff, whose DOIs have the same effect than those of Zootaxa.
WE NEED TO UPDATE THE BIBLIO MODULE TO VERSION 1.2 to solve some of these problems, which I also requested almost one year ago, on Jan 28, 2020. See Biblio-module updates #6124
There is no lack of reporting from the users' side.
We need that the journal issue, article and subarticle level DOIs are mapped correctly. They are correctly coded from the publishers' side. The problem is in our side.
The problem also creates multiple concatenated article titles and multiple repetitions of the whole author set that then need to be deleted manually, an often onerous work.
Do not try to fix this issue alone. Contact the author of the original module so that you can actually solve it, hopefully before another year passes.
Cheers,
Carlos

**Comment by PaulKiddle** [comment]
Seems like we have a patch for this that doesn't work (https://github.com/NaturalHistoryMuseum/scratchpads2/blob/master/sites/all/modules/patches/biblio-prevent-concatenation-of-urls.patch)

A possible actual fix is here: https://www.drupal.org/project/biblio/issues/2832502

**Comment by alycejenni** [comment]
[2.9.17.1](http://scratchpads.org/news/2021-05/scratchpads-release-2917) now released
