### ISSUE TITLE
Distribution map  on wrong page

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6303]
- Added by [Iain MacGowan](http://lonchaeidae.myspecies.info/user/2)
- Scratchpad: [Lonchaeidae Online](http://lonchaeidae.myspecies.info)

### Description:

Lonchaeidae online
On the individual species pages I get the map displayed on the "Descriptions" page and not on the "Maps" page  - how can I change this?
thanks  ........  Iain

**Comment by PaulKiddle** [comment]
Hi Iain,

For some species pages ([example](http://lonchaeidae.myspecies.info/taxonomy/term/2072/descriptions)), there is a map on the Descriptions tab because this data is from the [taxon description entry (ecology and distribution)](http://lonchaeidae.myspecies.info/node/2273/edit).

The Maps tab on the other hand will only contain a map if the species has a Specimen/Observation record - only one of your species has one of these, [Dasiops ensifer](http://lonchaeidae.myspecies.info/taxonomy/term/1901/maps)/[CNMHS - LON 1 - 1234 l ](http://lonchaeidae.myspecies.info/node/2209).

Unfortunately there's no easy way to move the distribution map to the maps tab - however you can disable the maps tab in your [taxonomy settings](http://lonchaeidae.myspecies.info/admin/structure/taxonomy/classification_and_species_info/edit)

**Comment by Archilegt** [comment]
Hi, @PaulKiddle,
The map of Dasiops ensifer should display a dot or square for the locality, but I don't see anything. It may be that the link between locations and their display on the Maps tab is broken.

**Comment by PaulKiddle** [comment]
Looks like the specimen/observation record doesn't actually have a location associated with it, in fact the location field has been removed from this data type. This is quite an unusual configuration choice for a scratchpad, and since the specimen/observations aren't generally being used anyway I would recommend just removing the maps tab from that taxonomy.

**Comment by alycejenni** [comment]
Added brief explanation to [the wiki](https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Adjust-Maps-Settings#maps-on-species-pages).
