### ISSUE TITLE
Some "citekeys" not retrieved

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6351]
**Describe the bug**
In Myriatrix Scratchpads, some "citekeys" are not retrieved.
"Citekey 1067 not found". See http://myriatrix.myspecies.info/taxonomy/term/6570/descriptions
"Citekey 1093 not found". See http://myriatrix.myspecies.info/taxonomy/term/38503/descriptions

It could be that there is some biblio indexing problem and that the biblio NID is not correctly detected when citing literature. Maybe the biblio database or those two citations could be reindexed and the problems solved? Any help would be greatly appreciated!

**Comment by PaulKiddle** [comment]
It seems that the [bib] tags use citekey rather than NID - in some cases citekey is the same as the NID, in other cases it is different. My guess would be that uploaded/imported biblio records have the citekey pre-specified, while manually added records just use the NID. Afaik there's no way to see or edit the citekey in scratchpads, I'm not sure if updating the biblio module will fix this but it's on my list of things to check now.

**Comment by PaulKiddle** [comment]
Using the BibTex export link at the bottom of the biblio page will let you see the citekey - for example for [Pauropoda (1067)](http://myriatrix.myspecies.info/content/pauropoda) it's [wirkner_chilopoda_2011](http://myriatrix.myspecies.info/biblio/export/bibtex/1067)

**Comment by Archilegt** [comment]
Hi Paul,
Thank you for checking that. It definitely indicates an incorrect indexing
problem, though I don't know neither the cause nor how to solve it.
"wirkner_chilopoda_2011" is an abbreviated citation, but the link
associated with it is still "
http://myriatrix.myspecies.info/biblio/export/bibtex/1067", which contains
"1067" which again takes us to the NID of the Pauropoda paper that I was
trying to cite. The polluting record in this case seems to be
http://myriatrix.myspecies.info/content/chilopoda-circulatory-system, which
you can see contains the elements "Wirkner", "Chilopoda", and "2011", which
instead has the NID 786.

**Comment by Archilegt** [comment]
Extra info: I think that I have used the "Clone" function in some or all of
those problematic references. The clone function may have a bug which is
creating wrong links between NIDs and citekeys.

**Comment by PaulKiddle** [comment]
I don't think it's an indexing issue, more a data integrity issue.
Looks like both of those biblio records have the same citekey, which would be explained by usage of the clone function.
Apparently the biblio module doesn't place a unique key restraint on the citekey field, which is an extra problem.

**Comment by Archilegt** [comment]
Thank you, Paul! I actually didn't know about the citekey before this
thread. I thought that we were using our unique identifiers (NID: GUID) for
all purposes and that there were no additional identifiers involved. It is
indeed a sensitive issue, as citation was always targeted to the NID, which
to the best of my knowledge is indeed unique unlike the citekey.

**Comment by PaulKiddle** [comment]
@Archilegt I've updated your scratchpad so you can see and edit the citekey for a biblio entry (on the edit page it's under the Identifiers tab).

Hope this is useful enough for you - you'll be able to easily find the citekey now for references, and should only need to update it when you clone nodes.
This is a database update so no code has been changed (I'm hesitant to mess around with biblio module or adjacent code too much).

The only other question I have is whether this should be default for all scratchpads, I'm on the side of "no" since I don't think [bib] is used by very many users.


For the record the change is this:

```sql
update biblio_field_type set visible=1 where fid=44;
```
