### ISSUE TITLE
Invalid certification error

### ISSUE THREAD

**Issue by Rainieria** [NaturalHistoryMuseum/scratchpads2#6397]
**Describe the bug**
On attempting to access a pdf file I get the message:
_Visiting an untrustworthy website has been prevented

One or more of this website's certificates are invalid, so we can't guarantee its authenticity. This happens when the website's owner hasn't updated the certificate in time, or if it's a fake site created by scammers. Visiting a website like this makes you more vulnerable to attack._
(I've got Kaspersky)

**To Reproduce**
Tell us what you were doing when you found the bug, or (even better) tell us the steps to recreate it ourselves.
1. Go to https://micropezids.myspecies.info/node/301
2. Click on M&T

**Screenshots**

**Your setup:**
 - Scratchpad URL: https://micropezids.myspecies.info/
 - Browser: Firefox

**Impact**
Is this a minor inconvenience, or is it making it completely impossible to work on your Scratchpad?
Completely impossible for a major proportion of the work

**Anything else?**
Other users are complaining

**Comment by jrdh** [comment]
Hi @Rainieria - this issue is a result of the switch to HTTPS on Scratchpads. To fix it for this page, I've just gone in and edited the page, replacing all the `http://www.micropezids.myspecies.info` references with `https://micropezids.myspecies.info` instead. If you're seeing this problem on other pages too, then you can make similar modifications by removing the `www.` part from the URL and repacing `http://` with `https://`.
