### ISSUE TITLE
"Resources" page not loading

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6495]
Myriatrix "Resources" page (https://myriatrix.myspecies.info/content/resources) is not loading or taking a long time to load. When loaded, the editing overlay is not showing up. I was able to edit that page smoothly yesterday Friday. No idea why it is not working today.

**Comment by BarryWarrington** [comment]
My site is not loading at all.

**Comment by poospiza** [comment]
My site is also not loading at all.
https://ethoikos.myspecies.info/

**Comment by BarryWarrington** [comment]
The extreme slowness and how frequent it is completely down is becoming a problem. Since the update, my site has been very slow at times, making it impossible to work on. It is disappointing having to apologise regularly to users who keep asking/telling me about the issues they are encountering.

**Comment by jpsullivan65** [comment]
Took 2 min 30 seconds right now to load Scratchpad main page.  Most infuriating is unwillingness of NHM people to communicate to us when they know there are issues affecting Scratchpads. How much effort is required to send status reports to Scratchpad admins?  Send out an email with a short message outlining issue and timeline to address it. It's as if we don't exist.

**Comment by therobyouknow** [comment]
linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6488

**Comment by jpsullivan65** [comment]
I searched my email including junk & trash for the message about the expected slowness. I didn't get it.  Was that emailed or just posted on GitHub? We shouldn't be expected to routinely visit GitHub to learn what's going on, but even doing that doesn't seem to usually be very enlightening.  I would like to get emails about known problems/expected problems/decisions re future support and developments that affect Scratchpads. I can't believe every admin of an active Scratchpad doesn't want this.

**Comment by therobyouknow** [comment]
@jpsullivan65 

> Took 2 min 30 seconds right now to load Scratchpad main page. 

I am aware of these performance issues and I apologise, these are being dealt with together in this issue: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6488

> Most infuriating is unwillingness of NHM people to communicate to us when they know there are issues affecting Scratchpads. How much effort is required to send status reports to Scratchpad admins? Send out an email with a short message outlining issue and timeline to address it. It's as if we don't exist.

I'm the main developer and lead on Scratchpads, so the buck does stop with me!  As regards communication and status reports: 

- a notice was sent out when the most recent release started, advising users to anticipate performance issues during and after the release: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6479 This provides an example of communication with regard to improvements and what we had hoped to be temporary issues
- and email with the above was also sent out on the Scratchpads email distribution
- the release contained improvements and was necessary to resolve some top functionality problems
- I'm aware of the performance issues and improvements in the next release are being looked into to reduce impact experienced: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6488#issuecomment-988904964
- but also, those performance issues need fixing ASAP, that same ticket raised 11 days ago, by me, records that awareness of those issues and is there to track progress: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6488#issuecomment-988904964 (as mentioned above).

I will need to determine if the performance issues are due to the roll out of the release or if they were already there before the release. I don't expect the release itself to have caused these issues, but rather the way it has been rolled out, the deployment mechanism, which I've advised about that this has to be reviewed before we do another release. I have observed related performance issues before the release, e.g. ajax errors: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6458

**Comment by jpsullivan65** [comment]
Glad to know you're on top of things and investigating.  Please see if I have fallen off the email list as I cannot find the email you refer to.   The last Scratchpads-related email I can find was Oct. 6 from Ben Scott about domain names.  What email do you have on file for mormyrids.myspecies.info  ?

**Comment by therobyouknow** [comment]
Hello again John, @jpsullivan65 

> I searched my email including junk & trash for the message about the expected slowness. I didn't get it. Was that emailed or just posted on GitHub? 

Both. The release notice, including advice on slowness was posted here on github: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6479 and in the Scratchpads email distribution list.

> We shouldn't be expected to routinely visit GitHub to learn what's going on, 

Github is the central place for tracking issues with Scratchpads, because the software for Scratchpads is also stored there, so they are closest together to link issues to the corresponding software changes that fix them. Github is therefore the most suitable tool we have for managing the ongoing development to Scratchpads.

If you want to see newest issues, e.g. for example when the release notice comes out use this filter: https://github.com/NaturalHistoryMuseum/scratchpads2/issues?q=is%3Aopen+is%3Aissue

If you want to see updates on issues, including on progress with releases and fixes to yours and other's issues, use:
https://github.com/NaturalHistoryMuseum/scratchpads2/issues?q=is%3Aopen+is%3Aissue+sort%3Aupdated-desc

These filters are also available through the sort drop down:

![image](https://user-images.githubusercontent.com/1080646/146685268-5e60b202-5bc7-4498-b2ac-c21c52bca9ba.png)

on: https://github.com/NaturalHistoryMuseum/scratchpads2/issues

Would the above address your point "We shouldn't be expected to routinely visit GitHub" - what would be other places you would want to learn about updates on Scratchpads?

I'm sorry that you missed the email on the Scratchpads distribution list. 

I acknowledge the Facebook Group for Scratchpads https://www.facebook.com/groups/665993564280327 But the github and the scratchpadss email distribution are where I will prioritise my attention to issues and providing updates.  I think it's best use of time if communications are on github and scratchpads email, and not on further channels.  I would want to use more time on addressing the issues than duplicating the communications on lots of channels.

> but even doing that doesn't seem to usually be very enlightening. 

Can you expand further on what how it can be made more enlightening?

> I would like to get emails about known problems/expected problems/decisions re future support and developments that affect Scratchpads. 

Noted, thank you. Anything with regard to issues, releases, improvements sent in email will always also be on github. While I will look into ensuring that email information is correct, having the information on github means that information is always there, it cannot be deleted like an email can. And for the aforementioned reasons, github enables issues to be linked, grouped, and linked to the improvements: it provides some more essential structure above the emails and Facebook group.

> I can't believe every admin of an active Scratchpad doesn't want this.

As advised there are more communications, with the scratchpads emails and github updates. I'm here to listen so that these can be tuned to be more useful as we go along. It is continuous improvement. 

Thank you so much for advising of your issues and your feedback and I look forward to further communications in the form of my updates and your further thoughts as they arise.

**Comment by therobyouknow** [comment]
> What email do you have on file for mormyrids.myspecies.info ?

@jpsullivan65 John, issue raised for this:

https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6496

**Comment by BarryWarrington** [comment]
I too have never received any emails advising of issues, apart from ones sent direct from Rob. 

My site seems to be working much quicker now thankfully. To be fair, Rob has replied and dealt with issues I’ve reported nice and quickly. Sometimes, the issues crop up at the weekend when I assume NHM aren’t working so not much can be done during that time.

**Comment by therobyouknow** [comment]
Thank you @BarryWarrington Yes you're right these issues will be looked at further during usual 'office' hours.

**Comment by poospiza** [comment]
> My site is also not loading at all. https://ethoikos.myspecies.info/

I accessed the site again about an hour ago today 20/12. It has been working ok

**Comment by Archilegt** [comment]
Resources page was responsive today, normal speed.

**Comment by jpsullivan65** [comment]
My site is working well today, also.  Seems like the first time I can say that in a couple months.

**Comment by jpsullivan65** [comment]
Rob, Thanks for your comments above and also for apparently ironing out whatever the problems were recently.  Maybe I have been dropped from the email distribution by mistake and so this is the source of my annoyance at always being in the dark about what's happening with my Scratchpad.  Please do see that I'm on that list. It sure seems that the past few months have been difficult ones in terms of reliable Scratchpad performance. It's working very well right now.  When things aren't working I always come up here to GitHub and sometimes see others reporting problems on their sites, but I don't see announcements from you or anyone else of the sort that inform me about what's going on. Every computing cluster I've used has a designated text field on their site for info about current system performance, noting anything that's down or out of order and notifications about updates and patches and when they'll be run.  I think Scratchpads needs something like that. Post it anywhere you like, just let us where to go to see it. I shouldn't have to spend a lot of time scanning through issues here on GitHub trying to determine if others are having problems like mine. If you know there are issues, you need to say so in a message to all of us. Updates of this sort this sent to the email list as needed and posted at the designated spot would make life a lot easier.
