### ISSUE TITLE
Missing Biography tabs

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6501]
Which tabs should be in a typical Biography/People page? 
These: View (active tab), Edit EXIF Settings, Forum/E-mail integration, OpenID identities, Publications, Shortcuts, Track, Contact
Example: https://myriatrix.myspecies.info/users/pdecker

All those tabs except "View" have disappeared from these two Biographies:
https://myriatrix.myspecies.info/users/archilegt
https://myriatrix.myspecies.info/users/asombke

Could you please restore the tabs for those two biographies? Feedback on what caused this issue is also welcome.

**Comment by therobyouknow** [comment]
Thank you for advising @Archilegt and in particular with regard to 'restore' - which says that these were visible in the past.

My initial guess is that the fix I did in 2.10 / 2.10.1 for https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6400 now requires some further logic to allow these tabs to show. But it might not be that.

Can you advise on the last time you had seen them working?  Don't worry if you can't, I can still investigate. But if you do know, then I could use that date last seen information to test my initial guess above.

**Comment by Archilegt** [comment]
Hi, Rob!
I really have no idea when the tabs disappeared. Also, I can't think of a connection that will cause only those two biographies to lose their tabs, unless that the "age" of the accounts has something to do. Those are the oldest accounts, 3+ years.
On the other hand, the content of the tabs is not gone, just the display is disrupted. For example, if you go to the accounts internally, via the menu People, find "asombke", and click on "edit", that will take you to Andy's account overlay, which will still show a bar on the top, containing all the buttons for the content that should be externally displayed as tabs. Internally, in the account overlay, you can still click on one of the buttons, for example "Publications", and that will take you to Andy's Publications tab, externally visible at: https://myriatrix.myspecies.info/user/3/biblio

**Comment by Archilegt** [comment]
Hi, @therobyouknow . Could you please take a look at this? I really need those two profiles showing their tabs. I can't really understand why just those two profiles were affected, but it should be possible to make the tabs display again, as they should. I imagine that you could internally look at the settings of the other profiles that are working, and change the archilegt and asombke settings accordingly. Maybe is some problem in the "manage view" settings or the like.

**Comment by therobyouknow** [comment]
This looks OK for

https://myriatrix.myspecies.info/users/pdecker

![image](https://user-images.githubusercontent.com/1080646/179272619-d12fc0f5-0f96-47f9-b485-4de0e1458a65.png)

@Archilegt is this now OK?

BUT

Not OK for

https://ichneumoninae.myspecies.info/users/davide-dal-pos

![image](https://user-images.githubusercontent.com/1080646/179272734-86e14824-d2ea-4e92-9891-5962f7480f99.png)

you only have the View tab.

**Comment by therobyouknow** [comment]
site database config needs to checking to see if problem. reviewed with ben

**Comment by therobyouknow** [comment]
The root cause of the missing tabs is this code change: https://github.com/NaturalHistoryMuseum/scratchpads2/commit/c16a224b449f34ab39bc1ce1497929c8fa1628ce#diff-e16cc2e59ada025bd9593ee88f17d9e38392bb7409de029f5a31d6f28898f5fb to fix issue: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6400

It's regression in the above fix. The above change used in the fix for #6400 is to hide tabs not required for taxonomy terms.   However, the problem is that hide will take effect on any page that has the same kind of tabs.  This is why the tabs are also missing from the user's page, which is the regression - i.e. fixing one thing broke something else.

I confirmed this is the root cause by commenting out the fix and observing the tabs now display.

![image](https://user-images.githubusercontent.com/1080646/181290064-ca01b16a-d2a5-4a12-a76e-8af946114964.png)

when logged out

![image](https://user-images.githubusercontent.com/1080646/181290297-81dc4587-e814-434a-9939-b6beadd6725b.png)

when logged in as maintainer

![image](https://user-images.githubusercontent.com/1080646/181290424-d789524f-6825-4a0e-a918-5dbebb4501ad.png)


The solution is to add a check to see what page we're on, in the `sites/all/themes/scratchpads/templates/region--content.tpl.php` code, to check that if we're on a user page, we don't apply the hide.

**Comment by Archilegt** [comment]
I confirm that the screenshots for "logged out" and "logged in" show how the biographies are meant to be visualized.

**Comment by therobyouknow** [comment]
**ongoing analysis, dev notes**

implementing solution - if on user page don't hide tabs.


![image](https://user-images.githubusercontent.com/1080646/186189681-2b3ef9d5-712c-409e-851a-5ca4e667e552.png)

**Comment by therobyouknow** [comment]
working solution, tabs for user now display as required ( https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6501#issuecomment-1196930009 - see also comment from site admin confirming as such). Test success:

![image](https://user-images.githubusercontent.com/1080646/186194515-86d374e4-c110-44c0-b588-0aee23ec924f.png)

Regression testing to ensure solution for #6400 still works:

(original test results here: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6400#issuecomment-984472924 )

`nontaxonomy/term/37297` - test ok:

![image](https://user-images.githubusercontent.com/1080646/186195202-4850e1fc-145f-4def-9dc6-b65d38125b1a.png)


`/morphology/scape` - test ok:

![image](https://user-images.githubusercontent.com/1080646/186195706-99c0aab1-1b13-4b90-8707-ecc11347bd85.png)

**Comment by Archilegt** [comment]
Hi, @therobyouknow! I sent you a voice message to your 008.

**Comment by therobyouknow** [comment]
Thank you for your message @Archilegt I listened all the way through.  I would like github tickets created for what you have talked about in the message and will listen again and aim to help you with creating those tickets.

I have made a fix and will now need to schedule the release which will be around mid September.  The release will include other fixes.

That fix I have made which I describe in my previous comment ( https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6501#issuecomment-1224218194 ) should meet your requirement as you advised here: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6501#issuecomment-1197044594  Can you confirm this is still the case please?

I would suggest that once we have established this fix does as required we can then look at further separate work based on tickets we make from your comments in the voice mail.

**Comment by therobyouknow** [comment]
Potentially fixed by solution for:
https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6501

**Comment by therobyouknow** [comment]
**regression testing**

Regression testing of that fix for #6501 shows it needs to be refined because some unwanted tabs are now reshowing for non-biological items. What needs to happen is that Drupal system function tabs (View, Edit, Clone etc) need to show, while Scratchpad domain specific tabs are not shown for non-biological tabs.

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1080646/202481972-664ff2a0-aa3f-41b4-be5c-9e9036d3c42e.png">

![image](https://user-images.githubusercontent.com/1080646/202482724-97bb1279-6069-49e7-8d98-1cb0b2dbec8e.png)

@Archilegt can you tell me if you want to see this tabs (as highlighted in red box) to appear again for 

https://myriatrix.myspecies.info/nontaxonomy/term/37297

Originally those tabs were hidden, except for `View` showing:

https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6400#issuecomment-984472924

**Comment by therobyouknow** [comment]
I'm going to come back to this ticket shortly, later today. But I need to work on something else in the sprint to come back after a break in thinking about it, with a fresh pair of eyes about how to ensure the correct tabs always show for various pages (users, terms, content). I think that's reasonable.  We have to get this right #6400 partially got it, but lack of regression testing caused this issue #6501.  I'd rather give myself time to get it right first or second time, rather than many more multiple goes at it giving the illusion of progress.

**Comment by therobyouknow** [comment]
**ongoing analysis, term page detection**

detect if on term page, then check bio or non-bio

**Comment by therobyouknow** [comment]
**solution complete and dev testing passed, including regression, now ready for release**

**fix restores tabs:**
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1080646/203721206-d72d727b-91f0-4ed3-9981-239f19d0ae07.png">

<img width="699" alt="image" src="https://user-images.githubusercontent.com/1080646/203721301-2628b7b4-ab53-4adb-9664-e8f36c7e8b36.png">





**Regression testing**

Ensuring that [solution for in issue 6400](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6400#issuecomment-984472924) still works:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/1080646/203720869-0dda2c19-d9ab-4db5-8059-f4d8f14f05ca.png">


<img width="832" alt="image" src="https://user-images.githubusercontent.com/1080646/203720997-5e626d77-2cf7-4aca-8ee7-62c256a4c8d1.png">

**Comment by therobyouknow** [comment]
Now released to your sites @Archilegt @DavideDalPos 



logged in:

https://myriatrix.myspecies.info/users/archilegt

![image](https://user-images.githubusercontent.com/1080646/212714461-a11482e1-72eb-41a6-b46c-20f0b63a408b.png)

https://myriatrix.myspecies.info/users/asombke

![image](https://user-images.githubusercontent.com/1080646/212721508-9105877a-401b-4e23-9fb6-b93d21bfd0d3.png)

logged out:

https://myriatrix.myspecies.info/users/archilegt

![image](https://user-images.githubusercontent.com/1080646/212715784-d69ab9d3-df1a-4d79-8f6a-293dd2a47d77.png)

https://myriatrix.myspecies.info/users/asombke

![image](https://user-images.githubusercontent.com/1080646/212721836-6a2678d3-015e-47a6-95b7-a228717dc85f.png)





logged in:

https://ichneumoninae.myspecies.info/users/davide-dal-pos

![image](https://user-images.githubusercontent.com/1080646/212721293-da901b47-6645-4319-b3f7-5d448fc7a567.png)



logged out:

![image](https://user-images.githubusercontent.com/1080646/212721130-3b6755b4-2fe9-4695-a00b-560f40a471b1.png)

**Comment by Archilegt** [comment]
I can confirm that the fix is working on my side! Thank you, Rob!
