### ISSUE TITLE
I forgot my password BUT not email received to reset it

### ISSUE THREAD

**Issue by ybraet** [NaturalHistoryMuseum/scratchpads2#6518]
Dear all,

on one of my website https://doryctinaekey.myspecies.info/user/password I am trying to log in but  I forgot my password.
So I ask to reset it. But even after clicking on the button to resset + filling all the field, I never receive an email to my email address.
and nothing is in the spam box.

Please could you solve this issue urgently?

Thank you for your help!! And Happy new year 2022!!

**Comment by Archilegt** [comment]
@ybraet, this is because the system emails are not going out at all.

@therobyouknow, we need one more manual password here.

Linking #6507

**Comment by ybraet** [comment]
Dear all,
Hopefully, I have retrieved my password. But yes I agree very strongly to have a backup way to retrieve the password
BestYves

    Le samedi 29 janvier 2022, 22:48:04 UTC+1, Archilegt ***@***.***> a écrit :  
 
 


@ybraet, this is because the system emails are not going out at all.

@therobyouknow, we need one more manual password here.

Linking #6507

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by therobyouknow** [comment]
linking https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447

**Comment by therobyouknow** [comment]
I am now tracking this problem in this issue https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6447 

This helps me centralise the tracking of the same problems so that I can more quickly record my investigation to progress the solution and for other developers to find where I've got to to be able to contribute as well.

Therefore I am closing this issue #6518 because it is being tracked in #6447, but don't worry I am still working on the problem and tracking it in #6447.

Thank you very much for raising it. 

Please always continue to raise an issue if you see a problem. If it appears to be the same as an existing issue I will mark it as such as a duplicate and link it to the existing issue.  

Don't worry - I'm very happy to hear about new issues - I always want to hear about them. 

My marking as duplicate is just part of the standard process of understanding a problem to provide a solution as soon as possible.
