### ISSUE TITLE
Blue pin missing in Location

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6521]
**Describe the bug**
The blue pins pointing locations are not showing up in Myriatrix. Just an empty bounding box appears. The bounding box does contain the correct latitude/longitude information though. 
For an example of how the blue pins look like see #6390.
For an example of locality not showing the blue pin in Myriatrix see Lake Sandoval https://myriatrix.myspecies.info/content/lake-sandoval
For an example of a specimen from Lake Sandoval not showing the blue pin see https://myriatrix.myspecies.info/content/zmmu-myr-peru-131-2019
Clicking on the empty bounding box correctly shows:
Latitude: -12.61333
Longitude: -69.0325
Coordinate uncertainty in meters: 30

This should be a minor fix, e.g., figuring out why the pin thumbnail is not displaying within its bounding box.

**Comment by therobyouknow** [comment]
Working on this now for you @Archilegt - this is what I will be doing this morning:

1 - check that I can see the issue you see, which I expect to, thank you for the links
2 - checking the site settings to see if adjustment could solve
3 - if not, checking browser console logs and Drupal dblogs / watchdog logs for errors
4 - if new information for settings from logs analysis, re-try step 2
5 - if not, start further analysis to possibly extend beyond today, xdebug of copy of site on my own machine



> Hi, Rob! Could you please lend me a hand with the display of the “blue
> dropped pins” on the maps in Myriatrix? I have few locations added, but for
> those that are in there, the blue pin display is broken and just the
> “bounding box” is shown. I would be very happy if the display is restored.

**Comment by Archilegt** [comment]
Blue pins also gone (at least on my side) for https://alkcarb.myrocks.info
Example of page where I can't see the pins: Bolivia https://alkcarb.myrocks.info/nontaxonomy/term/143
Down on that page there is the green banner "Occurrences", with a map and six pins that are not displayed. Maybe Emma can confirm.
Screenshot by Rob, posted nine days ago on #6388 shows blue pins visible on his side. Maybe those settings could help.

**Comment by therobyouknow** [comment]
Thanks @Archilegt 

**1 - check that I can see the issue you see**

I'm at the step 1 of 5 of my previous comment: in the process of establishing the problem you are seeing on your site.   I would like to go through your observations above.  

_Don't worry: I know there is a problem with pins which I need to fix._  

But I need to make sure I've fully understood all of the problem. So I'll start from the beginning:

**Establishing examples of the problem**

> "Blue pin missing in Location." 

> "The blue pins pointing locations are not showing up in Myriatrix. Just an empty bounding box appears. The bounding box does contain the correct latitude/longitude information though."

In comment https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6521#issue-1124850883

"For an example of locality not showing the blue pin in Myriatrix see Lake Sandoval https://myriatrix.myspecies.info/content/lake-sandoval" - when I click on that link I see:

![image](https://user-images.githubusercontent.com/1080646/179213190-74df8c0b-23df-4304-9b55-5d3a5c8fca8e.png)

and zooming in

![image](https://user-images.githubusercontent.com/1080646/179213305-a604b579-8fd7-4331-94e5-80893aae75cb.png)

So there _is_ a blue pin.  However, I appreciate that there is still an issue here but I need to know what it is. 

When you say: "locality not showing" - what is not showing here?  Is there something else that should be shown as well as the pin?

I note your example "For an example of how the blue pins look like see https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6390." :

![image](https://user-images.githubusercontent.com/1080646/179213667-247fc504-1726-44d0-b83f-ae86a8321ffd.png)

This looks like it is working the same as https://myriatrix.myspecies.info/content/lake-sandoval in the blue pegs are appearing.

What is missing @Archilegt ?  Please illustrate this using screenshots if you can and if possible annotations or accomanying text description.

Again, don't worry! I believe you when you say there is an issue but I need to understand fully what it is.

**Comment by Archilegt** [comment]
Hi, Rob. There is some magic on your side that makes the blue pins/pegs show up. On my side:
Myriatrix:
![image](https://user-images.githubusercontent.com/60008120/179216162-0291773b-344c-42c1-b409-1b4c4cca0832.png)

Alkcarb:
![image](https://user-images.githubusercontent.com/60008120/179216403-d99be2c3-edd5-484c-88ec-255baaa508f4.png)

**Comment by therobyouknow** [comment]
@Archilegt I've come back to this, this afternoon as promised.

The screenshots are really useful to help me understand. Thank you very much!

From them, I can see that the pin is attempted to be plotted on the map.   It looks like the image for the pin has not been fetched successfully but the browser has attempted to plot with no image.

Now I understand what you mean by the bounding box - it's the outline rectangle we see here:

![image](https://user-images.githubusercontent.com/1080646/179241144-98f03634-d7e4-439a-8797-46f2bb435356.png)

Yes bounding box is a correct technical term in terms of CSS and HTML technical terminology, from various documentation I've read on the subject.

Previous to this though, in this context I had thought "bounding box" was referring to a shape on the map, a polygon of some sort to outline a region in the country. Now I understand!

**Some initial solutions to consider**

- Forgive me if you've done this already: have you tried clearing your web browser cache fully before visiting the page?
- Are any of your colleagues or people you know seeing the same issue on their devices?
- Perhaps try on a mobile phone.

If at least one of the above shows the pins are showing then I would think it was something to do with the particular machine.

If not: i.e. your colleagues/friends are seeing the same issue or on other devices, then 2 other things we could look at:

1 - First of those 2 things:

_Assuming you've fully cleared the browser cache, history and cookies and the problem is still there_, in Chrome, open a new browser window and right click and select inspect:

![image](https://user-images.githubusercontent.com/1080646/179249636-ed809605-152e-4c0b-9095-f9caa6533f3b.png)

A new Devtools window will open.

Then in your browser, go to: https://myriatrix.myspecies.info/content/lake-sandoval

Go back to the Devtools window and select Network

![image](https://user-images.githubusercontent.com/1080646/179249938-a4830944-b4ac-471a-854e-e297c33e157c.png)

Then, go down to  Status and click to sort, see if you can see any red messages items - if you do please post them here.

![image](https://user-images.githubusercontent.com/1080646/179250169-977b019e-4f4b-4e4f-baf4-9ddff8c4c3a5.png)

Then click on Console and post any red messages you see there, here.


Second of those 2 things.

Can you advise me of your setup - browser and version, operating system and version, and your geographical location.  The geographical location might be significant and perhaps a firewall is blocking some traffic requests from the browser for some locations. I can't think of any that would be affected, nor why this would happen.  But with such geographical information, I can attempt to simulate your location with the VPN I have. I can also speak to our TS infrastructure team about it too.

**Comment by Archilegt** [comment]
Hi, Rob. Many thanks for your feedback. I confirm that the problem persists:
- On mobile device, iOS 12, Safari browser
- On mobile device, iOS 15, Safari browser
- On laptop, Windows 10, Finland, for an extended period of time and Firefox versions until the latest (v102.0) and Chrome
- On another computer, from a colleague in Germany, at least until yesterday. I don't know the settings.
So, the issue spans over at least two countries, three browsers, and four devices.

**Comment by Archilegt** [comment]
I cleared the entire cache in Chrome and can confirm that the problem persists for Myriatrix and Alkcarb

**Comment by Archilegt** [comment]
The problem seems to be related to "marker-icon-2x.png", which is the "blue pin/peg" that we should see within the bounding box. Compare to "marker-shadow.png", the shadow of the pin/peg, which does show within the b.b.

![image](https://user-images.githubusercontent.com/60008120/179262764-8f9e966a-d9a8-42e8-bc88-e508450da649.png)

**Comment by therobyouknow** [comment]
Confirming I can the problem on macOS Safari Version 15.5 (17613.2.7.1.8)

<img width="1325" alt="Screenshot 2022-07-18 at 16 02 37" src="https://user-images.githubusercontent.com/1080646/179542104-0fa2be36-6561-4106-98a2-5d7f1bdb94ee.png">


Thank you @Archilegt for your screenshot of the Console - that is very useful.

![image](https://user-images.githubusercontent.com/1080646/179543024-e702508e-9866-489f-a3d4-8ec31d7cf080.png)

Useful because your screenshot of the Console shows errors that indicate an issue with mixed http and https requests / http non-secure requests are being made with a https secure call.   The correction for this is to have everything https.

I think the reason why some browsers like Chrome don't have the missing pin is that their default settings are tolerant of the above incorrect mixed http/https requests.  Meanwhile other browsers like Safari seem to have more stricter settings by default and the problem is seen.

Now for me to see how I can make all content requests https.

**Comment by therobyouknow** [comment]
The insecure link seen in that Console log, is being used I think because https on the server is not detected. Here is the code that attempts this detection: https://github.com/NaturalHistoryMuseum/scratchpads2/blob/1336cf7ac586e11756a105353726ecd94278ae3c/sites/all/modules/contrib/sharethis/sharethis.module#L479

https is implemented at the firewall which "wraps around the server", so it's not surprising, I'd say, that it's not detected on the server. That's my thinking so far.

I'm not sure how this about observation relates to the missing pin. `marker-icon-2x.png` doesn't appear to exist at the path shown in the Console log, i.e. in here: https://github.com/NaturalHistoryMuseum/scratchpads2/tree/master/sites/all/modules/custom/gm3/images/marker

So my thinking is that `marker-icon-2x.png` could be defined in the config or content - that's where I'll look next.

**Comment by therobyouknow** [comment]
**Ongoing analysis**

I am seeing the mixed content http/https error even when the blue peg appears.   So from that I'd say it's not related to the root cause if it happens either way.

**Comment by therobyouknow** [comment]
**Ongoing analysis and solutions** 

where it works:
https://myriatrix.myspecies.info/sites/all/modules/custom/gm3/images/marker/blue.png

where it doesn't work - broken image (bounding box) shown:
https://myriatrix.myspecies.info/sites/all/modules/custom/gm3/images/marker/marker-icon-2x.png

I think different pin image graphic is being selected depending on the pixel densite of the device (retina vs non-retina).  

Specifically I think for ultra high resolution displays, marker-icon-2x.png is attempted and if not that type of display, then blue.png is used. There's a clue in the name with the 2x  too.  I think the comment: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6521#issuecomment-1185663871 corroborates this: most of the devices where the problem is seen are iOS, which at those versions will have retina displays. A Windows device is also mentioned and perhaps this has a ultra high resolution display as well.  I also see the problem on Safari and Chrome on my MacBookPro 2016 16" which has a "2880 x 1800 retina display" - quoted from the "About this mac" menu option.

Inspection of the page html markup for https://myriatrix.myspecies.info/content/lake-sandoval shows the different image for working and non working in:

Working - Chrome on Ubuntu:

![image](https://user-images.githubusercontent.com/1080646/179737191-97212551-9301-40df-8825-ebb2acbdf33e.png)

Non-working - macOS Safari

![image](https://user-images.githubusercontent.com/1080646/179738071-e004f1a7-530b-44c4-88fc-586e99f859c8.png)

I think the decision for selection is being done in javascript in the custom gm3 module.


**Solution - short term**

Similar to what was suggested here:

https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6521#issuecomment-1185704913

`sites/all/modules/custom/gm3/images/marker/marker-icon-2x.png` is missing. So on the production site file system I would copy the `blue.png` icon to a new file called `marker-icon-2x.png` then test.  I am expecting the possibility that this  `marker-icon-2x.png` copy of `blue.png` might be the wrong size for retina displays - i.e. perhaps too small. I will check this in testing.  If it is indeed too small then I will adjust the `marker-icon-2x.png` image to display larger.

I would expect this can be done without going through a release.

**Solution - long term**

Put the above changes into the source code to include in a future release. This will mean that the change will always be there in future releases.

I would also be looking at the gm3 module separately.  I'm unsure what custom code is needed to plot pegs on a map.   The community contrib module https://www.drupal.org/project/geolocation module does a very good job for plotting pegs on a map. The less custom code and more community code we have the better.

I'll work on the short term solution now and follow up here.

**Comment by therobyouknow** [comment]
@Archilegt please have a look now. I have done a fix.


![image](https://user-images.githubusercontent.com/1080646/179782353-2a22911f-f436-482f-8100-c326b714771c.png)


![image](https://user-images.githubusercontent.com/1080646/179782389-e34efd4c-4054-4d80-8031-873c1d1e694a.png)


Aforementioned "Solution - short term" to copy copy the blue.png icon to a new file called marker-icon-2x.png then test.  Image size looks fine but will await confirmation from @Archilegt 

Remaining work:
- get confirmation from @Archilegt that this is fine
- prepare this for a forthcoming release so as to be permanently in the codebase and appear in all future releases

**Comment by Archilegt** [comment]
Hi, Rob! I can confirm that the fix is working for Lake Sandoval. It also works for other location (Peru: Lima: mountain near Asia, https://myriatrix.myspecies.info/content/peru-lima-mountain-near-asia). Many thanks! I am closing this issue, but see comment below. You can also reopen it if needed.

From your comment above:
"I would also be looking at the gm3 module separately. I'm unsure what custom code is needed to plot pegs on a map. The community contrib module https://www.drupal.org/project/geolocation module does a very good job for plotting pegs on a map. The less custom code and more community code we have the better."
The possibility of using the Geolocation Field module is appealing for several reasons, including the Geometry Support, Map providers, and Map features. However, this is not as simple as replacing custom code by that module. The reason is that there is an entire content type built for Scratchpads: the **"Location" content type**. Fields on that content type must be consistent with the specifications for class "Location" and its properties as defined in DarwinCore (https://dwc.tdwg.org/terms/#location) and DublinCore (http://purl.org/dc/terms/Location). Moreover, the Location content type has dependencies specific to Scratchpads: the **"Specimen/Observation" content type** and the **"Taxon description" content type**. Any change to how Locations are managed should disrupt neither the dependencies nor **the DarwinCore export** of Scratchpads.

My recommendation would be working together in updating the Location content type and documenting the changes **after** Scratchpads is migrated to Drupal 8 or superior (required for the suggested Geolocation Field module). An update is due anyway, as the properties of class Location in DarwinCore have improved in recent years.

Kind regards,
Carlos
