### ISSUE TITLE
Front page error when attempt to edit it

### ISSUE THREAD

**Issue by scratchpads** [NaturalHistoryMuseum/scratchpads2#6532]
- Added by [Christos Georgiadis](https://icgf.myspecies.info/user/2)
- Scratchpad: [Κέντρο Απογραφής της Πανίδας της Ελλάδας - Greek Fauna Documentation Center](https://icgf.myspecies.info)

### Description:

I keep on getting an error (unexpected error...) when I try to Edit the front page of the website. 
https://icgf.myspecies.info/#overlay-context=&overlay=scratchpads-front/edit

**Comment by therobyouknow** [comment]
Related: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6516

**Comment by therobyouknow** [comment]
confirming I can see the same issue as you.

Analysing the site. I am currently working out how your front page is constructed.

I've turned on db logs module, which I think will give more information about the error in the watchdog logs.

**Comment by therobyouknow** [comment]
**ongoing analysis**

dblogs / watchdog logging enabled, this is now working and shows a number of errors that give me clues to the root cause of this issue.

**Location:** https://icgf.myspecies.info/scratchpads-front/edit
**Message:** Notice: Undefined index: block_1 in views_db_object->get_items() (line 2549 of /var/aegir/platforms/scratchpads-2.10.1/sites/all/modules/contrib/views/includes/view.inc).

**Location:** https://icgf.myspecies.info/scratchpads-front/edit
**Message:** Notice: Trying to get property 'handler' of non-object in views_db_object->get_items() (line 2549 of /var/aegir/platforms/scratchpads-2.10.1/sites/all/modules/contrib/views/includes/view.inc).

**Location:** https://icgf.myspecies.info/scratchpads-front/edit
**Message:** Error: Call to a member function get_option() on null in views_db_object->get_items() (line 2549 of /var/aegir/platforms/scratchpads-2.10.1/sites/all/modules/contrib/views/includes/view.inc).

I've included the above messages as text as well as a screenshot of the logs, to aid searchability for general troubleshooting knowledge base.

I should note that just because a log entry is `Notice` doesn't mean it's insignificant; the severity is arbitrarily chosen by the developer at the time of writing the code.

Based on the above three log entries, it looks like there is a missing configuration - a missing Drupal block or Views display for the front page edit facility.

I also note that the URL for editing the front page appears to me to be a bit unusual: https://icgf.myspecies.info/scratchpads-front/edit   Instead, I would have expected something like: `https://icgf.myspecies.info/node/1/edit` where the `1` is the node id - it could be another number on this site. Though having said that, this URL pattern works for another site, https://myriatrix.myspecies.info/#overlay=scratchpads-front/edit 


![image](https://user-images.githubusercontent.com/1080646/182619474-96f0cdfa-d5d1-44af-91bb-ba46d5f7f1fe.png)

**Comment by therobyouknow** [comment]
**ongoing analysis, dev notes**

among the aforementioned errors, `block_1` was referred to, which is a Views display.   I referenced another site and found it to be defined there:  https://myriatrix.myspecies.info/admin/structure/views/view/front_page_blocks/edit

But Views module wasn't enabled on this site, so this needed to be enabled - and could have potentially solved the fatal error, if the config was still present and now active once the View module was enabled.

Views wasn't enabled because a) it did not appear as an option on the Structure menu and b) in the module list, it was shown as 'disabled' in any other modules that depended on it. 

I should note that Views module is listed twice in the modules list, presumably because as multisites, there is a local site specific instance of Views and a common instance of Views. The Views modules had to be enabled as mentioned for it to appear as a section in the structure admin page.

Having enabled Views, the config for `block_1` and other things is now available https://icgf.myspecies.info/admin/structure/views/view/front_page_blocks/edit

This looks just about the same as the equivalent on another site https://myriatrix.myspecies.info/admin/structure/views/view/front_page_blocks/edit

See side by side comparison below:

![image](https://user-images.githubusercontent.com/1080646/182658234-8c3d68c7-396c-4405-bba9-0b9fa9d153ec.png)

So with a cache clear, I was hopeful that visiting https://icgf.myspecies.info/scratchpads-front/edit would now work, i.e. not give an error.

Unfortunately, the same error occurs, with what appears to be the same error log entries in the log before.

So the next step will be to xdebug a local personal copy of this site and step through the code.

I note that there is a custom module `sites/all/modules/custom/scratchpads/scratchpads_front` which provides the `/scratchpads-front` and `/scratchpads-front/edit` URL paths - for all sites, including for the other site I compared with, where it works: https://myriatrix.myspecies.info/scratchpads-front/edit

So it's not a URL specific to this site where the issue is.

**Comment by benscott** [comment]
Could you try taking a look at scratchpads_front_page_edit form?  It loads views to offer options to configure the home page - and it sounds like one of those views / views displays is missing, causing the error.  I think users can configure a custom view/block to display, which if then deleted/missing would also cause this error.

**Comment by therobyouknow** [comment]
**ongoing analysis**

> Could you try taking a look at scratchpads_front_page_edit form? It loads views to offer options to configure the home page - and it sounds like one of those views / views displays is missing, causing the error. I think users can configure a custom view/block to display, which if then deleted/missing would also cause this error.

Thank you Ben, yes I am familiar with the code for this `scratchpads_front_page_edit` - it's the call back function to assemble to form will display the form for the `scratchpads-front/edit` route / URL path.   The routing here so that the URL shows that form is done in an implementation of hook_menu in Drupal 7, in this case in the scratchpads_front module.

As per earlier comment, I discovered that Views wasn't enabled, because it didn't list as an option in Structure admin menu, even though there is another listing of Views enabled. So the above could not have worked until then, but that's not all of the solution as the page still errors with what look to be similar errors. The code cites `block_1` which is now present with Views enabled and the config active.  So xdebug will get to the bottom of this.

**Comment by therobyouknow** [comment]
**ongoing analysis, dev notes**

`xdebug` now setup.  On Windows 11 WSL2 Ubuntu 20.04. 💪 💪 💪 💥 🐎 🐎 

I've spent today setting this up.  I've done it before several times on Windows 10.

This means I can run a copy of your site on my personal setup and run diagnostics, trace, debug and troubleshoot with the most powerful tools available.  I'd say this to the error: "I'm coming for you!"

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1080646/183265267-92f9120d-dac5-4e82-adc8-8f2a7abdee99.png">

**Comment by therobyouknow** [comment]
**ongoing analysis, dev notes**

Debugging `scratchpads_front_page_edit`


![image](https://user-images.githubusercontent.com/1080646/183376732-0e19ec49-fafa-43ee-8912-7435c563a1d7.png)

**Comment by therobyouknow** [comment]
**ongoing analysis**

Discussed with Ben Scott.  We believe there's a bug in 2 places: 
1. how the blocks are referred to by their machine name, specifically when there is only one block display, a singleton, in a View
2. how those blocks are referenced by the front page editor, specifically by that machine name for referencing those singleton blocks

The solution would be a code change to make 1) and 2) consistent with how they specify machine names.

**Comment by therobyouknow** [comment]
**ongoing analysis, dev notes: proposed solution**

**solution summary**

I think the solution is to remove 2 lines from the `block` table in the site database.  

**reasoning**

This is because I think the the `block` table has become out of sync/inconsistent with the corresponding Drupal Views displays actually available.

How did this happen?  I think a database transaction in the past failed to executely, thereby only partially done, leaving the `block` table inconsistent with the Drupal Views displays available.  I think the failure could have been due to server infrastructure outage. Such inconsistencies are not uncommon, from my experience and I have applied similar proposed remedies to correct database entries directly in other cases I've seen.

**analysis leading to reasoning**

In the query to list the views display block in the block table, shown below, I have highlighted three lines for `species_description` View block displays.  The `species_description`  View only has one block display. So there shouldn't be 3 listed here. I propose that 2 are duplicates must be deleted so that 1 is remaining.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/1080646/184922466-7232c803-bb00-4d0d-b7e6-e550eaec5be1.png">

In that same `block` table, referring to the above screenshot, if we look at the other Views, we can see that none of those have duplicate block entries like `species_description`  View description does.

Function `scratchpads_front_blocks_as_options` in  `scratchpads_front` has a for loop that iterates through the `block` table: https://github.com/NaturalHistoryMuseum/scratchpads2/blob/e4b17615004e2d2147f9633d5fdddbf133a86384/sites/all/modules/custom/scratchpads/scratchpads_front/scratchpads_front.module#L837

When the loop reaches the first of the blocks for `species_description` this will be row:

`| 114 | views  | species_description-block_1      | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |`

line 849 `$view_and_display = explode('-', $block->delta);` gets the block id for the view display `block_1`  But this is going to fail and cause the three errors and for the edit screen to fail to show https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6532#issuecomment-1203963680 

I can see that is going to fail stepping through the code in the xdebug debugger:

In line 2459 of view.inc we have a variable, `display_id` with value `block_1`.  This value comes from the `block` table and is the from the first row of the 3 entries from `species_description` in that table.

<img width="960" alt="Screenshot 2022-08-16 162721" src="https://user-images.githubusercontent.com/1080646/184926192-cb4eaa7c-3120-4b35-b849-626d761fd008.png">

From this screenshot below, we can see that the array of displays for `species_description` is of size 2. There are 2 Views displays for this View: the default (which is always there for a View) and the other display out of the 2 is only block views display. This single block views display had id `block`. So using the value in `display_id` is going to fail.

<img width="959" alt="Screenshot 2022-08-16 162823" src="https://user-images.githubusercontent.com/1080646/184925992-24e55b3a-db95-46a2-9fcc-3548591f4908.png">

To prove it fails. Using the call stack I set a break point in the calling code in scratchpads_front_blocks_as_options at line 854. If line 853 was successful then we'd proceed onto 854 and the breakpoint would be hit. But it did not get hit because an Exception would have been raised on the attempt to operate on the null value as a result of the `block_1` index value giving nothing.


<img width="960" alt="Screenshot 2022-08-16 163205" src="https://user-images.githubusercontent.com/1080646/184927802-29e374c1-fe80-4a47-a393-3d8f652669d3.png">


So going back to the `block` table query listing.  I now need to confirm which 2 lines I need to remove from it out of those 3.  Maybe this might be obvious: remove both rows with `block_1` leaving just the one with `block` .


I must test this on my personal local development setup copy of the site first and if successful in that the edit page shows, try to determine some further regression testing to check if nothing else affected. Then re-use the query on production once reviewed.

`drush sqlc` will allow me to perform queries to do the row delete.

**Comment by therobyouknow** [comment]
Further observation supporting my previous comment:

> When the loop reaches the first of the blocks for species_description this will be row:
> 
> `| 114 | views | species_description-block_1 | scratchpads | 0 | 0 | -1 | 0 | 0 | | | -1 |`

This block is the one where the failure happens as said and its id is 114.

I also talked about 2 rows to be removed to resolve this issue as being a database inconsistency. I think 114 above should be one of them, the other I think should be 175.

Looking at that whole table, putting the inconsistency with `species_description` View aside for the moment, I can see that the each row has a `scratchpads` and `scratchpads_admin` counterpart (for the `theme` column/field).  It seems odd that our code at the beginning of `scratchpads_front_blocks_as_options` is  a query getting _both_ `scratchpads_admin` and `scratchpads`. But the https://scratchpads-dev.ddev.site/scratchpads-front/edit path is an admin only path, so I'd be inclined to think we'd only need just the rows with  `scratchpads_admin` but maybe there's a reason for that.

I should also look at `block` table in other scratchpads sites to see if how `species_description` looks there.

**Comment by therobyouknow** [comment]
**ongoing analysis, dev note**

> I should also look at `block` table in other scratchpads sites to see if how `species_description` looks there.

I have looked at another site's block table in their database, mosquito-taxonomic-inventory.  

Conclusion comparing with another site:  they don't have the same issue of multiple entries for `species_description`. On that basis, that helps re-inforce my analysis and resulting proposal to remove the lines for icfg site as aforementioned.

```
MySQL [db]> select * from block where block.module = "views";
+-----+--------+----------------------------------+-------------+--------+--------+--------+--------+------------+-------+-------+-------+
| bid | module | delta                            | theme       | status | weight | region | custom | visibility | pages | title | cache |
+-----+--------+----------------------------------+-------------+--------+--------+--------+--------+------------+-------+-------+-------+
|  70 | views  | species_nomenclature-block       | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  71 | views  | species_slideshow-block          | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  72 | views  | species_description-block        | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  73 | views  | species_overview_map-block       | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  74 | views  | species_biblio-block             | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  75 | views  | species_map-block                | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  76 | views  | species_location-block           | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  77 | views  | species_media-block              | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  78 | views  | species_spm-block                | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  79 | views  | og_members-block_1               | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  80 | views  | front_page_blocks-block_1        | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  81 | views  | front_page_blocks-block_2        | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  82 | views  | front_page_blocks-block_3        | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  83 | views  | front_page_slideshow-block_1     | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  84 | views  | front_page_content-block         | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |     8 |
|  85 | views  | f1e06bda7de42a4d0be1915ce9b2b9e0 | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  86 | views  | d302f2c17c796ca5a549c23be7208580 | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  87 | views  | aab5a3c124fdc5f353a0194e2041f1d9 | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 111 | views  | og_members_block-block           | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 112 | views  | og_members_block-block_1         | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 113 | views  | og_my-block_1                    | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 126 | views  | 16c4f7a3670b362537e67e77d3c889f7 | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 129 | views  | tweets-block                     | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 132 | views  | taxonomy_revision-block_1        | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 133 | views  | taxonomy_revision-block_2        | scratchpads |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 235 | views  | 16c4f7a3670b362537e67e77d3c889f7 | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 236 | views  | aab5a3c124fdc5f353a0194e2041f1d9 | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 237 | views  | d302f2c17c796ca5a549c23be7208580 | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 238 | views  | f1e06bda7de42a4d0be1915ce9b2b9e0 | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 239 | views  | front_page_blocks-block_1        | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 240 | views  | front_page_blocks-block_2        | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 241 | views  | front_page_blocks-block_3        | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 242 | views  | front_page_content-block         | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |     8 |
| 243 | views  | front_page_slideshow-block_1     | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 244 | views  | og_members_block-block           | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 245 | views  | og_members_block-block_1         | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 246 | views  | og_members-block_1               | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 247 | views  | og_my-block_1                    | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 248 | views  | species_biblio-block             | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 249 | views  | species_description-block        | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 250 | views  | species_location-block           | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 251 | views  | species_map-block                | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 252 | views  | species_media-block              | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 253 | views  | species_nomenclature-block       | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 254 | views  | species_overview_map-block       | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 255 | views  | species_slideshow-block          | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 256 | views  | species_spm-block                | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 257 | views  | taxonomy_revision-block_1        | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 258 | views  | taxonomy_revision-block_2        | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 259 | views  | tweets-block                     | bartik      |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
+-----+--------+----------------------------------+-------------+--------+--------+--------+--------+------------+-------+-------+-------+
50 rows in set (0.001 sec)

```

**Comment by therobyouknow** [comment]
before 

```
MySQL [db]> select * from block where block.module = "views";
+-----+--------+----------------------------------+-------------------+--------+--------+--------+--------+------------+-------+-------+-------+
| bid | module | delta                            | theme             | status | weight | region | custom | visibility | pages | title | cache |
+-----+--------+----------------------------------+-------------------+--------+--------+--------+--------+------------+-------+-------+-------+
|  70 | views  | species_nomenclature-block       | scratchpads       |      1 |      0 |        |      1 |          0 |       |       |    -1 |
|  71 | views  | species_slideshow-block          | scratchpads       |      0 |    -23 | -1     |      0 |          0 |       |       |    -1 |
|  72 | views  | species_description-block        | scratchpads       |      1 |      0 |        |      0 |          0 |       |       |    -1 |
|  73 | views  | species_overview_map-block       | scratchpads       |      0 |    -24 | -1     |      0 |          0 |       |       |    -1 |
|  74 | views  | species_biblio-block             | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  75 | views  | species_map-block                | scratchpads       |      0 |    -25 | -1     |      0 |          0 |       |       |    -1 |
|  76 | views  | species_spm-block                | scratchpads       |      1 |      0 |        |      0 |          0 |       |       |    -1 |
|  77 | views  | species_media-block              | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  78 | views  | front_page_blocks-block_1        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  79 | views  | front_page_blocks-block_2        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  80 | views  | front_page_blocks-block_3        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  81 | views  | front_page_slideshow-block_1     | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  82 | views  | front_page_content-block         | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |     8 |
|  83 | views  | taxonomy_revision-block_1        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  84 | views  | taxonomy_revision-block_2        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  85 | views  | tweets-block                     | scratchpads       |      0 |    -26 | -1     |      0 |          0 |       |       |    -1 |
|  86 | views  | d302f2c17c796ca5a549c23be7208580 | scratchpads       |      0 |    -22 | -1     |      0 |          0 |       |       |    -1 |
|  87 | views  | 16c4f7a3670b362537e67e77d3c889f7 | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  88 | views  | aab5a3c124fdc5f353a0194e2041f1d9 | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  95 | views  | eol_images-block                 | scratchpads       |      1 |      0 |        |      2 |          1 |       |       |    -1 |
|  96 | views  | eol_videos-block                 | scratchpads       |      1 |      0 |        |      2 |          1 |       |       |    -1 |
|  97 | views  | eol_text-block                   | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 114 | views  | species_description-block_1      | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 174 | views  | species_description-block        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 175 | views  | species_description-block_1      | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 176 | views  | species_nomenclature-block       | scratchpads_admin |      0 |      0 | -1     |      1 |          0 |       |       |    -1 |
| 177 | views  | species_overview_map-block       | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 178 | views  | species_biblio-block             | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 179 | views  | species_spm-block                | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 180 | views  | eol_images-block                 | scratchpads_admin |      0 |      0 | -1     |      2 |          1 |       |       |    -1 |
| 181 | views  | eol_text-block                   | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 182 | views  | front_page_blocks-block_1        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 183 | views  | front_page_blocks-block_2        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 184 | views  | front_page_blocks-block_3        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 185 | views  | front_page_slideshow-block_1     | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 186 | views  | front_page_content-block         | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |     8 |
| 187 | views  | species_media-block              | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 188 | views  | tweets-block                     | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 189 | views  | species_slideshow-block          | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 190 | views  | species_map-block                | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 191 | views  | eol_videos-block                 | scratchpads_admin |      0 |      0 | -1     |      2 |          1 |       |       |    -1 |
| 192 | views  | d302f2c17c796ca5a549c23be7208580 | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 193 | views  | 16c4f7a3670b362537e67e77d3c889f7 | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 194 | views  | aab5a3c124fdc5f353a0194e2041f1d9 | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
+-----+--------+----------------------------------+-------------------+--------+--------+--------+--------+------------+-------+-------+-------+
44 rows in set (0.001 sec)
```

operation

```
MySQL [db]> use db;
Database changed
MySQL [db]> delete from block where block.bid = 114;
Query OK, 1 row affected (0.001 sec)

MySQL [db]> delete from block where block.bid = 175;
Query OK, 1 row affected (0.001 sec)

MySQL [db]>
```


after

```
MySQL [db]> select * from block where block.module = "views";
+-----+--------+----------------------------------+-------------------+--------+--------+--------+--------+------------+-------+-------+-------+
| bid | module | delta                            | theme             | status | weight | region | custom | visibility | pages | title | cache |
+-----+--------+----------------------------------+-------------------+--------+--------+--------+--------+------------+-------+-------+-------+
|  70 | views  | species_nomenclature-block       | scratchpads       |      1 |      0 |        |      1 |          0 |       |       |    -1 |
|  71 | views  | species_slideshow-block          | scratchpads       |      0 |    -23 | -1     |      0 |          0 |       |       |    -1 |
|  72 | views  | species_description-block        | scratchpads       |      1 |      0 |        |      0 |          0 |       |       |    -1 |
|  73 | views  | species_overview_map-block       | scratchpads       |      0 |    -24 | -1     |      0 |          0 |       |       |    -1 |
|  74 | views  | species_biblio-block             | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  75 | views  | species_map-block                | scratchpads       |      0 |    -25 | -1     |      0 |          0 |       |       |    -1 |
|  76 | views  | species_spm-block                | scratchpads       |      1 |      0 |        |      0 |          0 |       |       |    -1 |
|  77 | views  | species_media-block              | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  78 | views  | front_page_blocks-block_1        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  79 | views  | front_page_blocks-block_2        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  80 | views  | front_page_blocks-block_3        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  81 | views  | front_page_slideshow-block_1     | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  82 | views  | front_page_content-block         | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |     8 |
|  83 | views  | taxonomy_revision-block_1        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  84 | views  | taxonomy_revision-block_2        | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  85 | views  | tweets-block                     | scratchpads       |      0 |    -26 | -1     |      0 |          0 |       |       |    -1 |
|  86 | views  | d302f2c17c796ca5a549c23be7208580 | scratchpads       |      0 |    -22 | -1     |      0 |          0 |       |       |    -1 |
|  87 | views  | 16c4f7a3670b362537e67e77d3c889f7 | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  88 | views  | aab5a3c124fdc5f353a0194e2041f1d9 | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
|  95 | views  | eol_images-block                 | scratchpads       |      1 |      0 |        |      2 |          1 |       |       |    -1 |
|  96 | views  | eol_videos-block                 | scratchpads       |      1 |      0 |        |      2 |          1 |       |       |    -1 |
|  97 | views  | eol_text-block                   | scratchpads       |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 174 | views  | species_description-block        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 176 | views  | species_nomenclature-block       | scratchpads_admin |      0 |      0 | -1     |      1 |          0 |       |       |    -1 |
| 177 | views  | species_overview_map-block       | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 178 | views  | species_biblio-block             | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 179 | views  | species_spm-block                | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 180 | views  | eol_images-block                 | scratchpads_admin |      0 |      0 | -1     |      2 |          1 |       |       |    -1 |
| 181 | views  | eol_text-block                   | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 182 | views  | front_page_blocks-block_1        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 183 | views  | front_page_blocks-block_2        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 184 | views  | front_page_blocks-block_3        | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 185 | views  | front_page_slideshow-block_1     | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 186 | views  | front_page_content-block         | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |     8 |
| 187 | views  | species_media-block              | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 188 | views  | tweets-block                     | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 189 | views  | species_slideshow-block          | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 190 | views  | species_map-block                | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 191 | views  | eol_videos-block                 | scratchpads_admin |      0 |      0 | -1     |      2 |          1 |       |       |    -1 |
| 192 | views  | d302f2c17c796ca5a549c23be7208580 | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 193 | views  | 16c4f7a3670b362537e67e77d3c889f7 | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
| 194 | views  | aab5a3c124fdc5f353a0194e2041f1d9 | scratchpads_admin |      0 |      0 | -1     |      0 |          0 |       |       |    -1 |
+-----+--------+----------------------------------+-------------------+--------+--------+--------+--------+------------+-------+-------+-------+
42 rows in set (0.001 sec)

MySQL [db]>
```

result on site `scratchpads-front/edit` path now works. Page loads and previous errors not seen ( https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6532#issuecomment-1203963680 )

![image](https://user-images.githubusercontent.com/1080646/185087763-1b883223-49ef-461e-8e99-5d72db4cc8f6.png)

**Comment by benscott** [comment]
Thanks for the investigation Rob.  I want to look into this in more detail to ensure the view display error is indeed database corruption before deleting any content from users' sites. Created new issue #6578 for me to track this & have cloned species description block display to fix the error on ICGF site.

**Comment by therobyouknow** [comment]
I do think we've done [enough analysis](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6532#issuecomment-1216856127) here already and found a solution, and we haven't come back to this ticket; I think we're creating superfluous work here. The only thing I would say, and as Ben suggested, is to perform the same database operation not manually as described but as a hook update. The benefit being a record in the code of the operation (even though we already have it here in github (and we could put in a dev section of the wiki), but it also means that deployment for all sites can be automated. Though not all sites are seeing the issue and the corruption could be specific to this site. We're holding up closing this ticket when we already have a solution.
