### ISSUE TITLE
+ boxes gone

### ISSUE THREAD

**Issue by Archilegt** [NaturalHistoryMuseum/scratchpads2#6565]
**Describe the bug**
`+` expand boxes are gone at the upper level of Myriatrix classification and are replaced by the text "Open". See https://myriatrix.myspecies.info/myriatrix/myriapoda
Please, fix the boxes so that the classification can be expanded. Thanks.

**Comment by therobyouknow** [comment]
Is this working for you now, @Archilegt 

I am seeing the boxes as required now, please let me know if you are also seeing this.

![image](https://user-images.githubusercontent.com/1080646/177310609-d5197ff3-72c7-41f3-8025-ba57b6994822.png)


![image](https://user-images.githubusercontent.com/1080646/177310482-52b044a8-cf1a-422f-9320-23c92e7e38a4.png)


If it was temporarily not working, then one explanation I could think might be that the cause was related to the recent outage: https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6566 though I note you reported this boxes missing issue before the outage. But perhaps there were some early symptoms of that outage that affected the boxes.
