### ISSUE TITLE
How-to export pages from mhp.myspecies.info

### ISSUE THREAD

**Issue by therobyouknow** [NaturalHistoryMuseum/scratchpads2#6601]
From @StephanImhof 

Dear Rob,
now I know how to export the taxonomy. Is there a way to export the
'pages', which are connected to the taxonomy items, along with it? If
not, can I export them at all?
I tried to use Import - Nodes - Excel file import - and then either
'Page' or 'Taxonomy description' (that's where our text on the taxonomic
history of the species is displayed), but did not succeed.

**Comment by therobyouknow** [comment]
![image](https://user-images.githubusercontent.com/1080646/200010348-ccb39c6e-2a3d-4cbf-a839-6a08b230ae39.png)

**Comment by therobyouknow** [comment]
From @stephanImhof by email:

> Another question: Where can I best include geographic information (apart
> from GBIF). So far we included those in the taxonomic history page of
> each species, but it would be nice if we could have a separate space for
> this information, attached to the species name.
> Thanks for any hint,
> Stephan
> 
> 
> Me again, Rob,
> in the meantime I figured that the geographic distribution is best
> included under 'Taxon descriptions' and therein under 'Ecology and
> Distribution'. There I can chose polygons or countries to indicate the
> places where the species has been found. This automatically appears
> under the flag 'Description' when consulting the species from the
> taxonomy. Beautiful!
> 
> However, again, how can I export this information out of my scratchpad?
> If this is not possible, I need to do double work in including the
> distribution in my scratchpad (see above) as well as in the excel file I
> exportet according to your instruction, lately.
> It would be great if I can export it all together, or at least in two steps.
> Thank's for listening!
> Stephan

Hello Stephan, can you try following my [steps above](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6601#issuecomment-1303793171) that I found to work and let me know how you get on.

**Comment by Archilegt** [comment]
It is too much effort to reply to training issues separately. Before there was a "Scratchpads helpdesk" but we don't have the staff anymore. Therefore, it is better to organize an online Scratchpads (re)training course where we reply to one question while demonstrating the workflow for everyone else. This should solve "training issues" in the short term. In the medium term, we should think of having 5-min training videos addressing very specific questions (rather than long videos with many questions), so that we can easily reply with a link to the proper tutorial. Nota Bene: A good quality 5-min video may take 2.5 hours of rehearsals and corrections, so the workload of creating tutorials should not be underestimated.
Taxon Description, including fields like Distribution and Habitat can be exported in Excel. There is no way to export the maps. This has to be part of a major development for Scratchpads 3.0, where we sit together with the user community and agree which geographic standards and data types need to be implemented for reducing duplicate work and enhancing interoperability. We will need a central Scratchpads repository which is not only able to store the Location content type and the usual coordinates, but also the custom polygons that are created by users as well as open access area layers from key providers. At the moment and to the best of my knowledge, custom polygons cannot be reused by "calling" them but I may be missing something. A workaround would be cloning one Taxon Description which already has the desired custom polygon but I haven't checked if custom polygons are indeed preserved during cloning.
So, two different tasks here:
1. Organize an online Scratchpads (re)training course for the active users. Aim at April 2023.
2. Discuss the "geography, distribution, and habitat" topic and aim at a phased, improved implementation in Scratchpads 3.0 within three years.

**Comment by Archilegt** [comment]
@StephanImhof:
See how I use the Taxon Description maps, Distribution field, and Habitat field:
https://myriatrix.myspecies.info/taxonomy/term/37257/descriptions
See how it was cited in a scientific note:
Jiménez SG, Chagas-Jr A (2022) First records of Dendrothereua linceci (Wood, 1867) (Chilopoda, Scutigeromorpha, Scutigeridae) in Colombia. Check List 18(5): 967-971. https://doi.org/10.15560/18.5.967
